# Generated by Django 3.2.3 on 2022-03-07 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nickname',
            new_name='nick_name',
        ),
    ]
